SUCCESS_MSG = 'عملیات با موفقیت انجام شد'
DENY_PERMISSSION = 'شما به این بخش دسترسی ندارید'
DENY_PAGE = 'شما به این صفحه دسترسی ندارید'
FAIL_MSG = 'عملیات با شکست انجام شد'
HOME_PAGE = 'base:home'
SUCCESS_TICKET = 'تیکت شما با موفقیت ثبت شد'
SUM_TITEL = 'مجموع'
EXCEL_MODE = 'application/ms-excel'
EXCEL_EXPORT_FILE = 'attachment; filename='
DATE_FORMAT = '%Y-%m-%d'
PAY_PAGE = 'pay:PayBase'
SENDLIST_PAGE = 'store/sendlist.html'
ZONE_NAME = "منطقه"
ADD_STORE_MSG = 'مقدار باید بصورت عدد و بصورت انگلیسی باشد و تعداد کارکتر مجاز باید بین 10 تا 12 باشد'