# Generated by Django 5.0.1 on 2026-01-04 11:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0201_alter_failuresub_organizationclose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(unique=True, verbose_name='ظرفیت (مترمکعب بر ساعت)')),
            ],
            options={
                'verbose_name': 'ظرفیت',
                'verbose_name_plural': 'ظرفیت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='EquipmentSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تأمین\u200cکننده')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد')),
            ],
            options={
                'verbose_name': 'تأمین\u200cکننده تجهیزات',
                'verbose_name_plural': 'تأمین\u200cکنندگان تجهیزات',
            },
        ),
        migrations.CreateModel(
            name='CNGStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(9999999)], verbose_name='کد جایگاه')),
                ('old_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='کد قدیمی جایگاه')),
                ('name', models.CharField(max_length=200, verbose_name='نام جایگاه')),
                ('owner_name', models.CharField(blank=True, max_length=200, verbose_name='نام جایگاه دار')),
                ('region', models.CharField(choices=[('غرب', 'غرب'), ('شرق', 'شرق'), ('جنوب', 'جنوب'), ('شمال', 'شمال'), ('مرکز', 'مرکز')], max_length=10, verbose_name='حوزه')),
                ('ownership_status', models.CharField(choices=[('تك منظوره خصوصي', 'تک منظوره خصوصی'), ('تك منظوره صنايع دفاع', 'تک منظوره صنایع دفاع'), ('تك منظوره غير خصوصي', 'تک منظوره غیر خصوصی'), ('دو منظوره خصوصي', 'دو منظوره خصوصی'), ('دو منظوره شركتي', 'دو منظوره شرکتی'), ('دو منظوره صنايع دفاع', 'دو منظوره صنایع دفاع'), ('دومنظوره غير خصوصي', 'دومنظوره غیر خصوصی')], max_length=30, verbose_name='وضعیت مالکیت')),
                ('address', models.TextField(verbose_name='آدرس جایگاه')),
                ('equipment_progress', models.BooleanField(default=False, verbose_name='پیشرفت تولید تجهیزات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cng_stations', to='base.area', verbose_name='ناحیه')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cng_stations', to='base.city', verbose_name='شهر')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cng_stations', to='base.zone', verbose_name='منطقه')),
            ],
            options={
                'verbose_name': 'جایگاه CNG',
                'verbose_name_plural': 'جایگاه\u200cهای CNG',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_code', models.PositiveIntegerField(verbose_name='کد تجهیز')),
                ('contract_number', models.CharField(max_length=100, verbose_name='قرارداد تجهیز')),
                ('dispenser_count', models.PositiveIntegerField(default=1, verbose_name='تعداد دیسپنسر')),
                ('input_pressure', models.PositiveIntegerField(choices=[(1, '1'), (60, '60'), (250, '250'), (750, '750')], verbose_name='فشار گاز ورودی')),
                ('installation_date', models.DateField(verbose_name='تاریخ راه\u200cاندازی')),
                ('temporary_delivery_date', models.DateField(verbose_name='تاریخ تحویل موقت')),
                ('permanent_delivery', models.BooleanField(default=False, verbose_name='تحویل دائم شده')),
                ('permanent_delivery_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل دائم')),
                ('status', models.CharField(choices=[('در حال ساخت', 'در حال ساخت'), ('راه اندازي شده تاييد نشده', 'راه\u200cاندازی شده تأیید نشده'), ('راه اندازي شده', 'راه\u200cاندازی شده'), ('جمع آوري شده', 'جمع\u200cآوری شده'), ('حذف شده', 'حذف شده')], max_length=30, verbose_name='وضعیت')),
                ('transport_status', models.CharField(choices=[('جايگاه', 'جایگاه'), ('منطقه', 'منطقه')], max_length=10, verbose_name='وضعیت حمل تجهیز')),
                ('priority_letter_number', models.CharField(blank=True, max_length=100, verbose_name='نامه اولویت ارسال')),
                ('priority_letter_date', models.DateField(blank=True, null=True, verbose_name='تاریخ نامه اولویت ارسال')),
                ('priority', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='اولویت ارسال')),
                ('removal_reason', models.TextField(blank=True, verbose_name='علت حذف')),
                ('removal_letter_number', models.CharField(blank=True, max_length=100, verbose_name='شماره نامه حذف')),
                ('removal_letter_date', models.DateField(blank=True, null=True, verbose_name='تاریخ نامه حذف')),
                ('used_equipment', models.BooleanField(default=False, verbose_name='تجهیز کارکرده')),
                ('start_letter_number', models.CharField(blank=True, max_length=100, verbose_name='شماره نامه شروع')),
                ('start_letter_date', models.DateField(blank=True, null=True, verbose_name='تاریخ نامه شروع')),
                ('usage_type', models.CharField(choices=[('سواري', 'سواری'), ('اتوبوسي', 'اتوبوسی'), ('اتوبوسي-سواري', 'اتوبوسی-سواری'), ('ايستگاه مادر-دختر', 'ایستگاه مادر-دختر')], max_length=20, verbose_name='کاربری')),
                ('transfer_letter_number', models.CharField(blank=True, max_length=100, verbose_name='شماره نامه واگذاری')),
                ('transfer_letter_date', models.DateField(blank=True, null=True, verbose_name='تاریخ نامه واگذاری')),
                ('non_private_transferred', models.BooleanField(default=False, verbose_name='غیرخصوصی واگذارشده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cng.capacity', verbose_name='ظرفیت (مترمکعب بر ساعت)')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='cng.cngstation', verbose_name='جایگاه')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cng.equipmentsupplier', verbose_name='سازنده تجهیز')),
            ],
            options={
                'verbose_name': 'تجهیز',
                'verbose_name_plural': 'تجهیزات',
            },
        ),
        migrations.CreateModel(
            name='StationMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=20, verbose_name='شماره میتر (اشتراک گاز)')),
                ('fee_type', models.PositiveIntegerField(choices=[(1, 'جایگاه\u200cهای غیرخصوصی با تجهیزات دولتی'), (2, 'جایگاه\u200cهای خصوصی با تجهیزات دولتی'), (3, 'جایگاه\u200cهای سرمایه\u200cگذاری خصوصی سایر شهرها'), (4, 'جایگاه\u200cهای سرمایه\u200cگذاری خصوصی کلان شهرها')], verbose_name='نوع کارمزد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='cng.cngstation', verbose_name='جایگاه')),
            ],
            options={
                'verbose_name': 'متر جایگاه',
                'verbose_name_plural': 'مترهای جایگاه',
            },
        ),
    ]
