from django.urls import path
from . import views, reports, autoexcel, api
from .views import AddReInitial
from .urls_api import urlpatterns as api_urls
from api.captcha import captcha_view
from .views import (
    UpdateGsModelSejjeli, CreatePumpSejjeli, UpdateMakhzanSejjeli, CreateMakhzanSejjeli, UpdatePumpSejjeli,
    TicketAnalysisView
)


app_name = 'base'

urlpatterns = [
    path('login/', views.UserLogin.as_view(), name='login'),
    path('veryfi/', views.verify, name='veryfi'),
    path('logout/', views.UserLogout.as_view(), name='logout'),
    path('', views.home, name='home'),
    path('saveRoles/', views.saveroles, name='saveRoles'),
    path('UserProfile/q=<str:id>', views.userprofile, name='UserProfile'),
    path('saveImg/<int:id>', views.saveimg, name='saveImg'),
    path('import_excel/', views.import_excel, name='import_excel'),
    path('ComposeTicket/', views.composeticket, name='ComposeTicket'),
    path('ForwardTickets/', views.forwardtickets, name='ForwardTickets'),
    path('CrudeTickets/', views.crudetickets, name='CrudeTickets'),
    path('erjatotek/', views.erjatotek, name='erjatotek'),
    path('ClosedTickets/', views.closedtickets, name='ClosedTickets'),
    path('RoleTickets/', views.roletickets, name='RoleTickets'),
    path('MyTickets/', views.mytickets, name='MyTickets'),
    path('UserList/', views.userlist, name='UserList'),
    path('TicketToExcel/', autoexcel.tickettoexcel, name='TicketToExcel'),
    path('AddGSRelation/<str:id>/', views.addgsrelation, name='AddGSRelation'),
    path('GsEdit/<str:id>/', views.gsedit, name='GsEdit'),
    path('nazelsList/', views.nazelslist, name='nazelsList'),
    path('editNazel/', views.editnazel, name='editNazel'),
    path('editnazels/', views.editnazels, name='editnazels'),
    path('SaveeditNazel/<int:id>/', views.saveeditnazel, name='SaveeditNazel'),
    path('NazelsStatus/', views.nazelsstatus, name='NazelsStatus'),
    path('NazelsStatusByManategh/', views.nazelsstatusbymanategh, name='NazelsStatusByManategh'),
    path('NazelsStatusByNavahy/<str:id>/', views.nazelsstatusbynavahy, name='NazelsStatusByNavahy'),
    path('NazelsStatusByGS/<str:id>/', views.nazelsstatusbygs, name='NazelsStatusByGS'),
    path('gsTickets/<str:id>/', views.gstickets, name='gsTickets'),
    path('MasterPinPad_Tickets/<int:id>/', views.masterpinpadtickets, name='MasterPinPad_Tickets'),
    path('MasterPinpad_Ticketnahye/<str:id>/', views.masterpinpadticketnahye, name='MasterPinpad_Ticketnahye'),
    path('MasterPinpad_TicketGs/<str:id>/', views.masterpinpadticketgs, name='MasterPinpad_TicketGs'),
    path('save_star/<int:id>/', views.save_star, name='save_star'),
    path('amarkharabigs/', views.amarkharabigs, name='amarkharabigs'),
    path('gssakoook/', views.gssakoook, name='gssakoook'),
    path('gssakoook2/', views.gssakoook2, name='gssakoook2'),
    path('import_excel_paydari/', views.import_excel_paydari, name='import_excel_paydari'),
    path('vieweditnazels/<int:id>/', views.vieweditnazels, name='vieweditnazels'),
    path('CrudeTicketstek/<int:id>/<int:code>/', views.crudeticketstek, name='CrudeTicketstek'),
    path('ckpaydari/', views.ckpaydari, name='ckpaydari'),
    path('master_pinpad_tickets_Toexcel/<int:_id>/', views.masterpinpadticketstoexcel,
         name='master_pinpad_tickets_Toexcel'),
    path('rep_napaydari/', views.rep_napaydari, name='rep_napaydari'),
    path('graph_ticket/', views.graph_ticket, name='graph_ticket'),
    path('reportticketdaily/', views.reportticketdaily, name='reportticketdaily'),
    path('gs_detail/<str:id>/', views.gs_detail, name='gs_detail'),
    path('export_ticket_xls/', views.export_ticket_xls, name='export_ticket_xls'),
    path('sendticketrpm/', views.sendticketrpm, name='sendticketrpm'),
    path('gs_list_arbain/', views.gs_list_arbain, name='gs_list_arbain'),
    path('listgs/', views.listgs, name='listgs'),
    path('gs-import-file/<int:id>/', views.gsimportfile, name='gs-import-file'),
    path('gs-import-sejelli/<int:id>/', views.gsimportsejelli, name='gs-import-sejelli'),
    path('gs-import-flouk/<int:id>/', views.gsimportflouk, name='gs-import-flouk'),
    path('reportipc/', views.reportipc, name='reportipc'),
    path('reportipchistort/<int:_id>/', views.reportipchistort, name='reportipchistort'),
    path('repnazelgs/', views.repnazelgs, name='repnazelgs'),
    path('updatesetting/', views.updatesetting, name='updatesetting'),
    path('reportgsticketmgr/<str:_id>/<str:_az>/<str:_ta>/', reports.reportgsticketmgr, name='reportgsticketmgr'),
    path('reportzoneticketmgr/', reports.reportzoneticketmgr, name='reportzoneticketmgr'),
    path('reporttecnesianmgr/', reports.reporttecnesianmgr, name='reporttecnesianmgr'),
    path('reportareaticketmgr/<str:_id>/<str:_az>/<str:_ta>/', reports.reportareaticketmgr, name='reportareaticketmgr'),
    path('sla/', views.sla, name='sla'),
    path('arealist/', views.arealist, name='arealist'),
    path('citylist/', views.citylist, name='citylist'),
    path('averagetickets/<int:id>/', views.averagetickets, name='averagetickets'),
    path('areaupdate/<int:_id>/', views.areaupdate, name='areaupdate'),
    path('cityupdate/<int:_id>/', views.cityupdate, name='cityupdate'),
    path('send_bulk_ticket/', views.send_bulk_ticket, name='send_bulk_ticket'),
    path('close_bulk_ticket/', views.close_bulk_ticket, name='close_bulk_ticket'),
    path('delete_bulk_ticket/', views.delete_bulk_ticket, name='delete_bulk_ticket'),
    path('autoclose_bulk_ticket/', views.autoclose_bulk_ticket, name='autoclose_bulk_ticket'),
    path('input_zone_table/', views.input_zone_table, name='input_zone_table'),
    path('input_coding_table/', views.input_coding_table, name='input_coding_table'),
    path('reportsla/', views.reportsla, name='reportsla'),
    path('checkipclog/', views.checkipclog, name='checkipclog'),
    path('addclosegs/<str:id>/', views.addclosegs, name='addclosegs'),
    path('addmoghgs/<str:id>/', views.addmoghgs, name='addmoghgs'),
    path('updateclosegs/<str:id>/', views.updateclosegs, name='updateclosegs'),
    path('updatemoghgs/<str:id>/', views.updatemoghgs, name='updatemoghgs'),
    path('reportnesbatgs/', reports.reportnesbatgs, name='reportnesbatgs'),
    path('storehistory/', views.storehistory, name='storehistory'),
    path('reportsla_conflig/', views.reportsla_conflig, name='reportsla_conflig'),
    path('technicianperformancereport/', views.technicianperformancereport, name='technicianperformancereport'),
    # path('autolocation/', views.autolocation, name='autolocation'),
    # path('newautolocation/', views.newautolocation, name='newautolocation'),
    path('gslogs/<str:_id>/', views.gslogs, name='gslogs'),
    path('ownerlogs/<str:_id>/', views.ownerlogs, name='ownerlogs'),
    path('tekprofile/<str:_id>/', views.tekprofile, name='tekprofile'),
    path('tekprofiles2/<str:_id>/', views.tekprofiles2, name='tekprofiles2'),
    path('tekprofiles3/<str:_id>/', views.tekprofiles3, name='tekprofiles3'),
    path('deletetekchild/<str:_id>/', views.deletetekchild, name='deletetekchild'),
    path('showimg/<int:_id>/<int:_st>/', views.showimg, name='showimg'),
    path('uploadownerfile/<int:_id>/<int:ownerid>/', views.uploadownerfile, name='uploadownerfile'),
    path('import_excel_gsinfo/', views.import_excel_gsinfo, name='import_excel_gsinfo'),
    path('check_tek_store/<int:_id>/', views.check_tek_store, name='check_tek_store'),
    path('import_arbain/', views.import_arbain, name='import_arbain'),
    path('reportSellticket/', views.reportSellticket, name='reportSellticket'),
    path('nesbat_tickets/<int:id>/', reports.nesbat_tickets, name='nesbat_tickets'),
    path('import_excel_mojodi/', views.import_excel_mojodi, name='import_excel_mojodi'),
    path('gsmalek/', views.gsmalek, name='gsmalek'),
    path('listreinitial/', views.listreinitial, name='listreinitial'),
    path('addreinitial/<int:pk>/', AddReInitial.as_view(), name='addreinitial'),
    path('acceptreinitial/<int:pk>/<int:st>/', views.acceptreinitial, name='acceptreinitial'),
    path('autoexcel/', autoexcel.autoexcel, name='autoexcel'),
    path('tryopenticket/<int:_id>/', views.tryopenticket, name='tryopenticket'),
    path('deleteticket/<int:_id>/', views.deleteticket, name='deleteticket'),
    path('mgrdashboard/', views.mgrdashboard, name='mgrdashboard'),
    path('pump_report/', views.pump_report, name='pump_report'),
    path('deleteclosesell/<int:_id>/', views.deleteclosesell, name='deleteclosesell'),
    path('parametrsgs/<str:_gsid>/<int:_id>/', views.parametrsgs, name='parametrsgs'),
    path('reportchardsh/', views.reportchardsh, name='reportchardsh'),
    path('captcha/', captcha_view, name='captcha_view'),
    path('my_view/', views.my_view, name='my_view'),
    path('schematic/<str:_id>/', views.schematic, name='schematic'),
    path('failure_analysis_report/', views.failure_analysis_report, name='failure_analysis_report'),
    path('gs/<int:gs_id>/sejelli/', views.manage_sejelli, name='manage_sejelli'),
    path('sejelli/<int:sejelli_id>/', views.sejelli_detail, name='sejelli_detail'),
    path('gs-sejelli/<int:pk>/edit/', UpdateGsModelSejjeli.as_view(), name='update_gs_sejelli'),
    path('sejelli/<int:sejelli_id>/pump/add/', CreatePumpSejjeli.as_view(), name='create_pump_sejelli'),
    path('pump-sejelli/<int:pk>/edit/', UpdatePumpSejjeli.as_view(), name='update_pump_sejelli'),
    path('sejelli/<int:sejelli_id>/makhzan/add/', CreateMakhzanSejjeli.as_view(), name='create_makhzan_sejelli'),
    path('ticket-analysis_re/', views.ticket_analysis_report, name='ticket_analysis_re'),
    path(
        'makhzan-sejelli/<int:sejelli_id>/update/<str:pk>/',
        UpdateMakhzanSejjeli.as_view(),
        name='update_makhzan_sejelli'
    ),
    path('pending_sejelli/', views.pending_sejelli_list, name='pending_sejelli_list'),
    path('sejelli_changes/<int:sejelli_id>/', views.sejelli_changes, name='sejelli_changes'),
    path('apply_sejelli_changes/<int:sejelli_id>/', views.apply_sejelli_changes, name='apply_sejelli_changes'),
    path('approval_sejjeli/<int:_id>/', views.approval_sejjeli, name='approval_sejjeli'),
    path('sejelli_approval_list/', views.sejelli_approval_list, name='sejelli_approval_list'),
    path('sejelliview/<int:sejelli_id>/', views.sejelli_view, name='sejelli_view'),
    path('print_detail/<int:sejelli_id>/', views.print_detail, name='print_detail'),
    path('ticket-analysis/', TicketAnalysisView.as_view(), name='ticket-analysis'),
    path('trend-report/', reports.ticket_trend_report, name='ticket_trend_report'),
    path('pump_ticket_percentage_report/', reports.pump_ticket_percentage_report, name='pump_ticket_percentage_report'),
    path('generate_failure_curve/', reports.generate_failure_curve, name='generate_failure_curve'),
    path('update_areaid/', views.update_areaid, name='update_areaid'),
    path('parametrs/edit/', views.parametrs_edit_view, name='parametrs-edit'),
    path('ticket_list_row/', views.ticket_list_row, name='ticket_list_row'),
    path('ticket_list_row_zone/<int:_zone>/<int:_year>/<str:_status>/', views.ticket_list_row_zone, name='ticket_list_row_zone'),
    path('sell-products/', views.sell_product_list, name='sell_product_list'),
    path('sell-products/add/', views.add_sell_product, name='add_sell_product'),
    path('mount-list', views.MountListView.as_view(), name='mount_list'),
    path('mount-create/', views.mount_create, name='mount_create'),
    path('mount-update/<int:pk>/', views.mount_update, name='mount_update'),
    path('toggle-active/<int:pk>/', views.mount_toggle_active, name='mount_toggle_active'),

]

urlpatterns += api_urls
