from django.urls import path
from . import views
from .views import DiscrepancyListView, DiscrepancyUpdateView, import_excel_waybill

app_name = 'sell'

urlpatterns = [
    path('createsell/<int:id>/', views.addsell, name='createsell'),
    path('crashhard/', views.crashhard, name='crashhard'),
    path('listsell/', views.listsell, name='listsell'),
    path('listcrash/', views.listcrash, name='listcrash'),
    path('deletesell/', views.deletecng, name='deletesell'),
    path('updatesell/<str:mydate>/<int:id>/', views.updatesell, name='updatesell'),
    path('printsell/<str:date>/<int:id>/', views.printsell, name='printsell'),
    path('printsell2/<str:date>/<int:id>/', views.printsell2, name='printsell2'),
    path('statistics_sell/<str:date>/<int:id>/', views.statistics_sell, name='statistics_sell'),
    path('reportsell/', views.reportsell, name='reportsell'),
    path('sellday/', views.sellday, name='sellday'),
    path('daftartolombe/', views.daftartolombe, name='daftartolombe'),
    path('addnazel/', views.addnazel, name='addnazel'),
    path('reportsellkol/', views.reportsellkol, name='reportsellkol'),
    path('nazelrow/', views.nazelrow, name='nazelrow'),
    path('nazelrow2/', views.nazelrow2, name='nazelrow2'),
    path('checkEnd/', views.checkEnd, name='checkEnd'),
    path('selectsell/', views.selectsell, name='selectsell'),
    path('dahe/', views.dahe, name='dahe'),
    path('sellmgr/', views.reportsellmgr, name='sellmgr'),
    path('scan_qrcode/', views.scan_qrcode, name='scan_qrcode'),
    path('graph_sell/', views.graph_sell, name='graph_sell'),
    path('reportsellkolanalis/', views.reportsellkolanalis, name='reportsellkolanalis'),
    path('accessclosegs/', views.accessclosegs, name='accessclosegs'),
    path('deactiveaccessclosegs/<int:id>/', views.deactiveaccessclosegs, name='deactiveaccessclosegs'),
    path('sell_contradiction/', views.sell_contradiction, name='sell_contradiction'),
    path('report_dosenotexist/', views.report_dosenotexist, name='report_dosenotexist'),
    path('report_dosenotexistgroup/<int:zone>/<str:datein>/', views.report_dosenotexistgroup, name='report_dosenotexistgroup'),
    path('report_sell_mgr_nahye/<str:mdate>/<str:mdate2>/<int:zoneid>/<int:far>/', views.report_sell_mgr_nahye, name='report_sell_mgr_nahye'),
    path('report_sell_mgr_gs/<str:mdate>/<str:mdate2>/<int:areaid>/<int:far>/', views.report_sell_mgr_gs, name='report_sell_mgr_gs'),
    path('pumplist/', views.pumplist, name='pumplist'),
    path('naftgazazad/', views.naftgazazad, name='naftgazazad'),
    path('sell_contradiction_area/', views.sell_contradiction_area, name='sell_contradiction_area'),
    path('acceptrpmqrcode/<int:ticket>/<str:lat>/<str:long>/<int:failure>/', views.acceptrpmqrcode, name='acceptrpmqrcode'),
    path('checksellapi/', views.checksellapi, name='checksellapi'),
    path('qrstart/', views.qrstart, name='qrstart'),
    path('mojodi/', views.mojodi, name='mojodi'),
    path('mojodi2', views.mojodi2, name='mojodi2'),
    path('errorpage/', views.errorpage, name='errorpage'),
    path('analysis_sell/', views.analysis_sell, name='analysis_sell'),
    path('changeselllist/', views.changeselllist, name='changeselllist'),
    path('analizchart/', views.analizchart, name='analizchart'),
    path('sendproduct/', views.sendproduct, name='sendproduct'),
    path('import_excel_oms/', views.import_excel_oms, name='import_excel_oms'),
    path('reportsellkolsum/', views.reportsellkolsum, name='reportsellkolsum'),
    path('far_to_nazel/', views.fartonazel, name='far_to_nazel'),
    path('updatemojodi/<int:_id>/<int:_po>/', views.updatemojodi, name='updatemojodi'),
    path('uploadsoratjalase/<int:_id>/', views.uploadsoratjalase, name='uploadsoratjalase'),
    path('change_sell_list/<int:_id>/', views.change_sell_list, name='change_sell_list'),
    path('discrepancies/', DiscrepancyListView.as_view(), name='discrepancy_list'),
    path('discrepancies/<int:pk>/', DiscrepancyUpdateView.as_view(), name='discrepancy_update'),
    path('import_excel_waybill/', views.import_excel_waybill, name='import_excel_waybill'),
    path('report-waybill-sell/', views.report_waybill_sell, name='report_waybill_sell'),
    path('report-waybill-sent/', views.report_waybill_sent, name='report_waybill_sent'),
    path('update_customer_code/<int:id>/', views.update_customer_code, name='update_customer_code'),
    path('waybill-receive/<int:gs_id>/', views.waybill_receive, name='waybill_receive'),
    path('policy-analysis/', views.PolicyAnalysisView.as_view(), name='policy_analysis'),
    path('policy-analysis/<int:policy_id>/', views.PolicyImpactAPI.as_view(), name='policy_impact_api'),
    path('policy-chart/<int:policy_id>/', views.PolicyComparisonChart.as_view(), name='policy_chart_api'),
    path('sellcardazad-report/', views.sellcardazad_report, name='sellcardazad_report'),
    path('sellcardazad-detail/<int:gs_id>/', views.sellcardazad_detail, name='sellcardazad_detail'),
    path('sellcardazad-comparison/', views.sellcardazad_comparison, name='sellcardazad_comparison'),


]
