# Generated by Django 5.0.1 on 2025-12-06 10:22

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0191_alter_failuresub_organizationclose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام نوع')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد نوع')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'نوع شرکت',
                'verbose_name_plural': 'انواع شرکت',
            },
        ),
        migrations.CreateModel(
            name='DistributorGasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع همکاری')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='شماره قرارداد')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(limit_choices_to={'distribution_profile__role': 'distributor'}, on_delete=django.db.models.deletion.CASCADE, to='base.owner', verbose_name='توزیع\u200cکننده')),
                ('gas_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.gsmodel', verbose_name='جایگاه سوخت')),
            ],
            options={
                'verbose_name': 'جایگاه توزیع\u200cکننده',
                'verbose_name_plural': 'جایگاه\u200cهای توزیع\u200cکننده\u200cها',
                'unique_together': {('distributor', 'gas_station')},
            },
        ),
        migrations.CreateModel(
            name='FuelDistributionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50, verbose_name='نوع گزارش')),
                ('period_start', django_jalali.db.models.jDateField(verbose_name='شروع دوره')),
                ('period_end', django_jalali.db.models.jDateField(verbose_name='پایان دوره')),
                ('report_data', models.JSONField(verbose_name='داده\u200cهای گزارش')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='fuel_reports/', verbose_name='فایل گزارش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='شرکت')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.owner', verbose_name='تولید کننده')),
            ],
            options={
                'verbose_name': 'گزارش توزیع',
                'verbose_name_plural': 'گزارش\u200cهای توزیع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(max_length=50, verbose_name='نوع مجوز')),
                ('license_number', models.CharField(max_length=100, unique=True, verbose_name='شماره مجوز')),
                ('issue_date', django_jalali.db.models.jDateField(verbose_name='تاریخ صدور')),
                ('expiry_date', django_jalali.db.models.jDateField(verbose_name='تاریخ انقضا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='fuel_licenses/', verbose_name='فایل مجوز')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'مجوز سوخت',
                'verbose_name_plural': 'مجوزهای سوخت',
            },
        ),
        migrations.CreateModel(
            name='FuelStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_imported', models.PositiveIntegerField(default=0, verbose_name='کل واردات')),
                ('total_distributed', models.PositiveIntegerField(default=0, verbose_name='کل توزیع شده')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='موجودی فعلی')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'موجودی سوخت',
                'verbose_name_plural': 'موجودی\u200cهای سوخت',
            },
        ),
        migrations.CreateModel(
            name='ImportToDistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', django_jalali.db.models.jDateField(verbose_name='تاریخ توزیع')),
                ('amount_liters', models.PositiveIntegerField(verbose_name='مقدار توزیع شده (لیتر)')),
                ('price_per_liter', models.PositiveIntegerField(verbose_name='نرخ هر لیتر (ریال)')),
                ('document_number', models.CharField(max_length=100, verbose_name='شماره سند توزیع')),
                ('transport_info', models.CharField(blank=True, max_length=200, verbose_name='اطلاعات حمل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(limit_choices_to={'distribution_profile__role': 'distributor'}, on_delete=django.db.models.deletion.CASCADE, to='base.owner', verbose_name='توزیع\u200cکننده')),
                ('distributor_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='شرکت توزیع\u200cکننده')),
            ],
            options={
                'verbose_name': 'توزیع به توزیع\u200cکننده',
                'verbose_name_plural': 'توزیع به توزیع\u200cکننده\u200cها',
                'ordering': ['-distribution_date'],
            },
        ),
        migrations.CreateModel(
            name='DistributionToGasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', django_jalali.db.models.jDateField(verbose_name='تاریخ تحویل')),
                ('amount_liters', models.PositiveIntegerField(verbose_name='مقدار تحویلی (لیتر)')),
                ('price_per_liter', models.PositiveIntegerField(verbose_name='نرخ هر لیتر به جایگاه (ریال)')),
                ('status', models.CharField(choices=[('scheduled', 'زمان\u200cبندی شده'), ('in_transit', 'در حال حمل'), ('delivered', 'تحویل شده'), ('cancelled', 'لغو شده')], default='scheduled', max_length=20)),
                ('delivery_document', models.CharField(blank=True, max_length=100, verbose_name='شماره سند تحویل')),
                ('driver_info', models.CharField(blank=True, max_length=200, verbose_name='اطلاعات راننده')),
                ('vehicle_info', models.CharField(blank=True, max_length=200, verbose_name='اطلاعات وسیله نقلیه')),
                ('received_confirmation', models.BooleanField(default=False, verbose_name='تأیید دریافت')),
                ('received_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ دریافت واقعی')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor_gas_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_distribution.distributorgasstation', verbose_name='جایگاه زیرمجموعه')),
                ('distributor_distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_distributions', to='fuel_distribution.importtodistributor', verbose_name='توزیع توزیع\u200cکننده')),
            ],
            options={
                'verbose_name': 'تحویل به جایگاه',
                'verbose_name_plural': 'تحویل به جایگاه\u200cها',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='SuperFuelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', django_jalali.db.models.jDateField(verbose_name='تاریخ واردات')),
                ('amount_liters', models.PositiveIntegerField(verbose_name='مقدار (لیتر)')),
                ('tracking_number', models.CharField(max_length=50, unique=True, verbose_name='شماره رهگیری واردات')),
                ('document_number', models.CharField(max_length=100, verbose_name='شماره سند واردات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('distributed', 'توزیع شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='شرکت واردکننده')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_imports', to='base.owner')),
                ('importer', models.ForeignKey(limit_choices_to={'distribution_profile__role': 'importer'}, on_delete=django.db.models.deletion.CASCADE, to='base.owner', verbose_name='واردکننده')),
            ],
            options={
                'verbose_name': 'ورود بنزین سوپر',
                'verbose_name_plural': 'ورود بنزین سوپر',
                'ordering': ['-import_date'],
            },
        ),
        migrations.AddField(
            model_name='importtodistributor',
            name='fuel_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='fuel_distribution.superfuelimport', verbose_name='ورودی بنزین'),
        ),
        migrations.CreateModel(
            name='UserDistributionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('importer', 'واردکننده'), ('distributor', 'توزیع\u200cکننده'), ('gas_station', 'جایگاه')], max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='شرکت مربوطه')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_profile', to='base.owner')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر توزیع',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران توزیع',
            },
        ),
    ]
