# Generated by Django 5.0.1 on 2025-12-06 12:14

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0192_alter_failuresub_organizationclose_and_more'),
        ('fuel_distribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectSaleToDistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', django_jalali.db.models.jDateField(verbose_name='تاریخ فروش')),
                ('amount_liters', models.PositiveIntegerField(verbose_name='مقدار (لیتر)')),
                ('price_per_liter', models.PositiveIntegerField(verbose_name='نرخ هر لیتر (ریال)')),
                ('total_price', models.PositiveIntegerField(editable=False, verbose_name='مبلغ کل (ریال)')),
                ('document_number', models.CharField(max_length=100, verbose_name='شماره سند فروش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(limit_choices_to={'distribution_profile__role': 'distributor'}, on_delete=django.db.models.deletion.CASCADE, related_name='direct_sales_as_distributor', to='base.owner', verbose_name='توزیع\u200cکننده')),
                ('importer', models.ForeignKey(limit_choices_to={'distribution_profile__role': 'importer'}, on_delete=django.db.models.deletion.CASCADE, related_name='direct_sales_as_importer', to='base.owner', verbose_name='واردکننده')),
            ],
            options={
                'verbose_name': 'فروش مستقیم به توزیع\u200cکننده',
                'verbose_name_plural': 'فروش\u200cهای مستقیم به توزیع\u200cکننده',
            },
        ),
    ]
