# Generated by Django 5.0.1 on 2025-12-24 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0197_alter_failuresub_organizationclose_and_more'),
        ('fuel_distribution', '0002_directsaletodistributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsid', models.CharField(max_length=50, verbose_name='شناسه عرضه کننده')),
                ('name', models.CharField(max_length=50, verbose_name='نام عرضه کننده')),
                ('address', models.CharField(max_length=50, verbose_name='آدرس')),
                ('phone', models.CharField(max_length=50, verbose_name='تلفن')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.owner', verbose_name='کاربر')),
            ],
        ),
        migrations.AlterField(
            model_name='distributorgasstation',
            name='gas_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_distribution.supermodel', verbose_name='جایگاه سوخت'),
        ),
    ]
