# Generated by Django 5.0.1 on 2025-12-24 11:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0198_alter_failuresub_organizationclose_and_more'),
        ('fuel_distribution', '0003_supermodel_alter_distributorgasstation_gas_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermodel',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supermodel',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Nazel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='شماره نازل')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product', verbose_name='نام فرآورده')),
                ('supermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_distribution.supermodel', verbose_name='نام عرضه کننده')),
            ],
        ),
    ]
