# Generated by Django 5.0.1 on 2025-12-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_distribution', '0004_supermodel_create_supermodel_update_nazel'),
    ]

    operations = [
        migrations.AddField(
            model_name='nazel',
            name='makhzan',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ظرفیت مخزن'),
        ),
    ]
