# Generated by Django 5.0.1 on 2025-12-24 12:14

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0199_alter_failuresub_organizationclose_and_more'),
        ('fuel_distribution', '0005_nazel_makhzan'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributiontogasstation',
            name='station_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات جایگاه'),
        ),
        migrations.AddField(
            model_name='distributiontogasstation',
            name='station_receipt_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره رسید جایگاه'),
        ),
        migrations.AddField(
            model_name='distributiontogasstation',
            name='station_received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_deliveries', to='base.owner', verbose_name='دریافت کننده در جایگاه'),
        ),
        migrations.AddField(
            model_name='distributiontogasstation',
            name='station_received_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ دریافت در جایگاه'),
        ),
        migrations.AlterField(
            model_name='distributiontogasstation',
            name='status',
            field=models.CharField(choices=[('scheduled', 'زمان\u200cبندی شده'), ('in_transit', 'در حال حمل'), ('delivered', 'تحویل شده'), ('received', 'دریافت شده توسط جایگاه'), ('cancelled', 'لغو شده')], default='scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='DailyProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', django_jalali.db.models.jDateField(verbose_name='تاریخ نرخ')),
                ('price_per_liter', models.PositiveIntegerField(verbose_name='نرخ هر لیتر (ریال)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product', verbose_name='فرآورده')),
                ('supermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='fuel_distribution.supermodel', verbose_name='عرضه کننده')),
            ],
            options={
                'verbose_name': 'نرخ روزانه فرآورده',
                'verbose_name_plural': 'نرخ\u200cهای روزانه فرآورده',
                'ordering': ['-price_date'],
                'unique_together': {('supermodel', 'product', 'price_date')},
            },
        ),
        migrations.CreateModel(
            name='NozzleSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', django_jalali.db.models.jDateField(verbose_name='تاریخ فروش')),
                ('start_counter', models.PositiveIntegerField(verbose_name='شماره اول وقت')),
                ('end_counter', models.PositiveIntegerField(verbose_name='شماره آخر وقت')),
                ('sold_liters', models.PositiveIntegerField(editable=False, verbose_name='لیتر فروخته شده')),
                ('price_per_liter', models.PositiveIntegerField(verbose_name='نرخ هر لیتر (ریال)')),
                ('total_amount', models.PositiveIntegerField(editable=False, verbose_name='مبلغ کل (ریال)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nozzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_distribution.nazel', verbose_name='نازل')),
                ('supermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_distribution.supermodel', verbose_name='عرضه کننده')),
            ],
            options={
                'verbose_name': 'فروش نازل',
                'verbose_name_plural': 'فروش\u200cهای نازل',
                'ordering': ['-sale_date'],
                'unique_together': {('nozzle', 'sale_date')},
            },
        ),
        migrations.CreateModel(
            name='SupplierDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', django_jalali.db.models.jDateField(verbose_name='تاریخ خلاصه')),
                ('total_sales_liters', models.PositiveIntegerField(default=0, verbose_name='کل فروش لیتر')),
                ('total_sales_amount', models.PositiveIntegerField(default=0, verbose_name='کل فروش ریال')),
                ('opening_inventory', models.PositiveIntegerField(default=0, verbose_name='موجودی اول روز')),
                ('closing_inventory', models.PositiveIntegerField(default=0, verbose_name='موجودی آخر روز')),
                ('calculated_closing', models.PositiveIntegerField(default=0, verbose_name='موجودی محاسباتی')),
                ('difference', models.IntegerField(default=0, verbose_name='اختلاف')),
                ('supermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_distribution.supermodel', verbose_name='عرضه کننده')),
            ],
            options={
                'verbose_name': 'خلاصه روزانه عرضه کننده',
                'verbose_name_plural': 'خلاصه روزانه عرضه کنندگان',
                'ordering': ['-summary_date'],
                'unique_together': {('supermodel', 'summary_date')},
            },
        ),
        migrations.CreateModel(
            name='SupplierTankInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_date', django_jalali.db.models.jDateField(verbose_name='تاریخ ثبت موجودی')),
                ('actual_quantity', models.PositiveIntegerField(verbose_name='مقدار واقعی (لیتر)')),
                ('calculated_quantity', models.PositiveIntegerField(verbose_name='مقدار محاسباتی (لیتر)')),
                ('difference', models.IntegerField(default=0, verbose_name='اختلاف')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product', verbose_name='فرآورده')),
                ('supermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_inventories', to='fuel_distribution.supermodel', verbose_name='عرضه کننده')),
            ],
            options={
                'verbose_name': 'موجودی واقعی مخزن',
                'verbose_name_plural': 'موجودی\u200cهای واقعی مخازن',
                'ordering': ['-tank_date'],
                'unique_together': {('supermodel', 'product', 'tank_date')},
            },
        ),
    ]
