# Generated by Django 5.0.1 on 2025-12-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_distribution', '0006_distributiontogasstation_station_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermodel',
            name='makhzan',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ظرفیت مخزن'),
        ),
        migrations.AlterField(
            model_name='nazel',
            name='makhzan',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='شماره مخزن'),
        ),
    ]
