# Generated by Django 5.0.1 on 2025-12-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_distribution', '0007_supermodel_makhzan_alter_nazel_makhzan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nozzlesale',
            name='sold_liters',
            field=models.PositiveIntegerField(verbose_name='لیتر فروخته شده'),
        ),
        migrations.AlterField(
            model_name='nozzlesale',
            name='total_amount',
            field=models.PositiveIntegerField(verbose_name='مبلغ کل (ریال)'),
        ),
    ]
