# Generated by Django 5.0.1 on 2025-12-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_distribution', '0008_alter_nozzlesale_sold_liters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nozzlesale',
            name='test_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='میزان آزمایش (لیتر)'),
        ),
    ]
