# Generated by Django 5.0.1 on 2025-12-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_distribution', '0009_nozzlesale_test_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdistributionprofile',
            name='managed_stations',
            field=models.ManyToManyField(blank=True, help_text='برای کاربران جایگاه: می\u200cتوانند چندین جایگاه را مدیریت کنند', related_name='managers', to='fuel_distribution.supermodel', verbose_name='جایگاه\u200cهای تحت مدیریت'),
        ),
    ]
