# Generated by Django 5.0.1 on 2025-12-30 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_distribution', '0010_userdistributionprofile_managed_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdistributionprofile',
            name='active_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_users', to='fuel_distribution.supermodel', verbose_name='جایگاه فعال فعلی'),
        ),
    ]
