# Generated by Django 5.0.1 on 2025-12-30 08:35

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0200_alter_failuresub_organizationclose_and_more'),
        ('fuel_distribution', '0011_userdistributionprofile_active_station'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='supermodel',
            managers=[
                ('object_role', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='supermodel',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.area', verbose_name='انتخاب ناحیه'),
        ),
    ]
