from django.urls import path
from . import views
from rest_framework import routers
from .views import (
    GetSellInfo,
    GetSellInfoV2,
    GetAreaList,
    GetDetailTicket,
    GetArzyabiItem,
    SetArzyabiItem,
    SetLock,
    GetLock,
    GetGSEdit,
    SetGSEdit,
    GetEditPump,
    SetEditPump,
    GetGsList,
    RepairDate,
    GsTicketView,
    GetSellInfoAll,
    GetSendSms,
    SendOtpToMalek,
    SetMarsole,
    GsInformation,
    GetEventsLogs,
    GsRisk,
    AlarmsMgr,
    ListSellApi,
    AddCloseSellApi,
    GetGsLocation,
    GetStartDate,
    TicketEventApi,
    AddEventApi, DellEventApi, GetSellInfoWeb, GetGsInfoBtmt, SetGsIsPayBtmt, GoAddress,
    GetLatoLong, GetPanEdit, SetPanEdit, CloseSell, OpenSell, ListNazelInfo, ListGsByZoneId, ListNazelByGsId,
    SaveChangeNazel, ShowImgTek, CityInArea, AddRemoveLock, RunRemoveLock, DeleteZonePack, RunErjaToTek, ErjaToTek,
    LockListApi, ShowLock, LastSellDore, GetModemList, WebhookReceiveWaybill, GetGsByArea, RunStore, AssignStore,
    AreaInZone, GsInCity, BrandInCert, QrTimeList, GetSellInfoAllV2

)
from .liveinfo import GetLiveInfo, GetLiveBohran

app_name = 'api'

urlpatterns = [
    path('captcha/', views.CaptchaView.as_view(), name='captcha'),
    path("get-sell-info/", GetSellInfo.as_view()),
    path("get-sell-info-v2/", GetSellInfoV2.as_view()),
    path("get-sell-info-all/", GetSellInfoAll.as_view()),
    path("get-sell-info-all-v2/", GetSellInfoAllV2.as_view()),
    path("get-area-info/", GetAreaList.as_view()),
    path("get-gs-info/", GetGsList.as_view()),
    path("set-gs-ispay-btmt/", SetGsIsPayBtmt.as_view()),
    path("get-gs-info-btmt/", GetGsInfoBtmt.as_view()),
    path("get-failure-info/", GetDetailTicket.as_view()),
    path("get-arzyabi-item/", GetArzyabiItem.as_view()),
    path("set-arzyabi-item/", SetArzyabiItem.as_view()),
    path("get-live-info/", GetLiveInfo.as_view()),
    path("get-live-bohran/", GetLiveBohran.as_view()),
    path("set-lock/", SetLock.as_view()),
    path("get-lock/", GetLock.as_view()),
    path("get-gs-edit/", GetGSEdit.as_view()),
    path("set-gs-edit/", SetGSEdit.as_view()),
    path("set-marsole/", SetMarsole.as_view()),
    path("get-edit-pump/", GetEditPump.as_view()),
    path("set-edit-pump/", SetEditPump.as_view()),
    path("repairDate/", RepairDate.as_view()),
    path("GsTicketView/", GsTicketView.as_view()),
    path("get-send-sms/", GetSendSms.as_view()),
    path("send-otp-to-malek/", SendOtpToMalek.as_view()),
    path('search/', views.serach_results, name='search'),
    path('gsinformation/', GsInformation.as_view()),
    path('geteventslogs/', GetEventsLogs.as_view()),
    path('get-risk/', GsRisk.as_view()),
    path('alarmsmgr/', AlarmsMgr.as_view()),
    path('listsellapi/', ListSellApi.as_view()),
    path('addclosesellapi/', AddCloseSellApi.as_view()),
    path('get-gs-location/', GetGsLocation.as_view()),
    path('get-gs-start_date/', GetStartDate.as_view()),
    path('ticketeventapi/', TicketEventApi.as_view()),
    path('addeventapi/', AddEventApi.as_view()),
    path('getsellinfoweb/', GetSellInfoWeb.as_view()),
    path('delleventapi/', DellEventApi.as_view(), name='delleventapi'),
    path('getlatolong/', GetLatoLong.as_view(), name='getlatolong'),
    path('gs-by-area/', GetGsByArea.as_view(), name='gs-by-area'),
    path('brandincert/', BrandInCert.as_view(), name='brandincert'),
    path('qrtimelist/', QrTimeList.as_view(), name='qrtimelist'),
    path('checkproduct/', views.checkproduct, name='checkproduct'),
    path('get-pan-edit/', GetPanEdit.as_view(), name='get-pan-edit'),
    path('set-pan-edit/', SetPanEdit.as_view(), name='set-pan-edit'),
    path('close-sell/', CloseSell.as_view(), name='close-sell'),
    path('open-sell/', OpenSell.as_view(), name='open-sell'),
    path('list-nazel-info/', ListNazelInfo.as_view(), name='list-nazel-info'),
    path('list-gs-by-zone-id/', ListGsByZoneId.as_view(), name='list-gs-by-zone-id'),
    path('list-nazel-by-gsid/', ListNazelByGsId.as_view(), name='list-nazel-by-gsid'),
    path('save-change-nazel/', SaveChangeNazel.as_view(), name='save-change-nazel'),
    path('areainzone/', AreaInZone.as_view(), name='areainzone'),
    path('cityinarea/', CityInArea.as_view(), name='cityinarea'),
    path('gsincity/', GsInCity.as_view(), name='gsincity'),
    path('showimgtek/', ShowImgTek.as_view(), name='showimgtek'),
    path('addremovelock/', AddRemoveLock.as_view(), name='addremovelock'),
    path('runremovelock/', RunRemoveLock.as_view(), name='runremovelock'),
    path('runstore/', RunStore.as_view(), name='runstore'),
    path('AssignStore/', AssignStore.as_view(), name='AssignStore'),
    path('LockListApi/', LockListApi.as_view(), name='LockListApi'),
    path('deletezonepack/', DeleteZonePack.as_view(), name='deletezonepack'),
    path('getmodemlist/', GetModemList.as_view(), name='getmodemlist'),
    path('runerjatotek/', RunErjaToTek.as_view(), name='runerjatotek'),
    path('ErjaToTek/', ErjaToTek.as_view(), name='ErjaToTek'),
    path('ShowLock/', ShowLock.as_view(), name='ShowLock'),
    path('lastselldore/', LastSellDore.as_view(), name='lastselldore'),
    path('goaddress/', GoAddress.as_view()),
    path('get-semat-for-role/', views.get_semat_for_role, name='get_semat_for_role'),
    path('waybill/', WebhookReceiveWaybill.as_view(), name='waybill-webhook'),
]

router = routers.SimpleRouter()

router.register('creategs', views.CreateGs, basename='creategs'),
router.register('createowner', views.CreateOwner, basename='createowner'),
router.register('addnazel', views.AddNazel, basename='addnazel'),
router.register('addnazel2', views.AddNazel2, basename='addnazel2'),
router.register('showdateSell', views.ShowDateSell, basename='showdateSell'),
router.register('showdateSell2', views.ShowDateSell2, basename='showdateSell2'),

urlpatterns += router.urls
